name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/fedora:latest
      # Fix SELinux for the built OSTree: https://github.com/coreos/rpm-ostree/issues/1943
      options: --privileged --security-opt label:disable
    steps:
      - name: Install dependencies
        run: dnf install -y rpm-ostree selinux-policy selinux-policy-targeted policycoreutils git

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build OSTree
        run: ./compose.sh
        
      # upload-artifact@v2 has trouble with tens of thousands of files
      - name: Create repo tarball
        run: tar -czf /var/tmp/repo.tar.gz -C /var/tmp/repo .

      - name: Create repository artifact
        uses: actions/upload-artifact@v2
        with:
          name: repository
          path: /var/tmp/repo.tar.gz
          retention-days: 5
    
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
  
      - name: Install Backblaze B2 command-line tool
        run: |
          python -m pip install --upgrade pip
          pip install --quiet --no-cache-dir b2==2.0.2

      - name: Sync to Backblaze B2
        run: |
          b2 authorize-account ${{ secrets.B2_APPKEY_ID }} ${{ secrets.B2_APPKEY }}
          b2 sync --delete --replaceNewer /var/tmp/repo/ b2://${{ secrets.B2_BUCKET }}/
          b2 clear-account